BEGIN;

ALTER TABLE IF EXISTS citizenai_learner ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS citizenai_attempt ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS citizenai_concept_mastery ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS citizenai_mock ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS citizenai_exam_outcome ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS citizenai_runtime_snapshot ENABLE ROW LEVEL SECURITY;

COMMIT;
